---

- name: Create a vip
  hosts: bigips
  connection: local
  tasks:

      - name: Create Pool
        bigip_pool:
            lb_method: least-connections-member
            user: COF5ADMN01
            password: Yi[ZuS%XH6[tyP{
            name: ansible-test123
            monitors:
              - https
            slow_ramp_time: 120
            server: "{{ inventory_hostname }}"
            validate_certs: false
        delegate_to: localhost     
