---
- name: create vip
  hosts: bigips
  connection: local

  tasks:
  - name: Create VIP
    uri:
      url: https://{{ inventory_hostname }}/mgmt/tm/ltm/virtual
      validate_certs: no
      method: POST
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      body: {"name": "redcard-paper-stage.target.com_80_ttc","mask": "255.255.255.255","destination": "/Common/10.68.113.209:80","enabled": true,"ipProtocol": "tcp","source": "0.0.0.0/0","vlans": ["/Common/VLANC1797"],"vlansEnabled": "true","pool": "/Common/nel","profiles":[{"name": "tcp"},{"name": "tcp","context": "all"}]}
      return_content: yes
      body_format: json
    register: virtual     
